Repository stereum-dev/ethereum-node, pull requests merged in 2022-09, with the labels that each got.

#622 ADD: Fee Recipient via API
  controls/roles/validator-fee-recipient-api/tasks/main.yml
  launcher/src/backend/ValidatorAccountManager.js
  launcher/src/background.js
  launcher/src/store/ControlService.js
Labels: enhancement

#733 FIX: update btns getting stuck
  launcher/src/components/UI/node-header/IconsNav.vue
  launcher/src/components/UI/node-header/UpdatePanel.vue
Labels: bug

#737 FIX: teku metrics to default (all categories)
  launcher/src/backend/ethereum-services/TekuBeaconService.js
Labels: bug

#742 ADD: (tests for) config update #738 #737
  controls/finishUpdate.yaml
  controls/roles/update-changes/.yamllint
  controls/roles/update-changes/molecule/20-rc3/converge.yml
  controls/roles/update-changes/molecule/20-rc3/molecule.yml
  controls/roles/update-changes/molecule/20-rc3/playbook.yml
  controls/roles/update-changes/molecule/20-rc3/prepare.yml
  controls/roles/update-changes/molecule/20-rc3/verify.yml
  controls/roles/update-changes/tasks/2.0-rc3/fix-graffiti-738.yaml
  controls/roles/update-changes/tasks/2.0-rc3/updates-20-rc3.yaml
  controls/roles/update-changes/tasks/main.yml
  controls/roles/update-changes/tests/test.yml
Labels: enhancement

#752 FIX: readme link to latest release
  README.md
Labels: documentation

#763 ADD: restart-services role & github actions molecule schedule
  .github/workflows/test-molecule.yml
  controls/roles/restart-services/.yamllint
  controls/roles/restart-services/molecule/default/converge.yml
  controls/roles/restart-services/molecule/default/create.yml
  controls/roles/restart-services/molecule/default/destroy.yml
  controls/roles/restart-services/molecule/default/molecule.yml
  controls/roles/restart-services/molecule/default/playbook.yml
  controls/roles/restart-services/molecule/default/prepare.yml
  controls/roles/restart-services/molecule/default/verify.yml
  controls/roles/restart-services/tasks/main.yml
  controls/roles/restart-services/tasks/restart-service.yaml
  controls/roles/restart-services/tests/test.yml
  launcher/src/backend/NodeConnection.js
  launcher/src/background.js
  launcher/src/components/UI/node-header/IconsNav.vue
  launcher/src/store/ControlService.js
Labels: enhancement

#775 FIX: update services molecule tests
  controls/roles/update-services/molecule/default/verify.yml
  controls/roles/update-services/molecule/single-service/verify.yml
Labels: bug

#777 FIX: readme adaptions to new version
  README.md
Labels: documentation

#792 FIX: Update readme
  README.md
Labels: documentation

#806 FIX: restart services after unattended update
  controls/stereum-services-update.sh
Labels: bug
