Repository stereum-dev/ethereum-node, pull requests merged in 2022-07, with the labels that each got.

#476 FIX: grafana not starting with prysm
  launcher/src/backend/ethereum-services/GrafanaService.js
Labels: bug

#477 ADD: closing dialog
  launcher/src/background.js
Labels: bug

#489 FIX: grafana
  launcher/src/backend/ethereum-services/GrafanaService.js
Labels: bug

#474 FIX: molecule tests
  controls/roles/manage-service/files/grafana/BesuService/dashboards/besu-overview_rev5.json
  controls/roles/manage-service/files/grafana/NethermindService/dashboards/nethermind.json
  controls/roles/manage-service/molecule/ssv-lighthouse/prepare.yml
  controls/roles/manage-service/molecule/ssv-lighthouse/verify.yml
  controls/roles/manage-service/molecule/ssv-nimbus/prepare.yml
  controls/roles/manage-service/molecule/ssv-nimbus/verify.yml
  controls/roles/manage-service/molecule/ssv-teku/prepare.yml
  controls/roles/manage-service/molecule/ssv-teku/verify.yml
Labels: bug

#492 FIX: no overwrite of install path while setup
  controls/roles/setup/tasks/main.yml
  launcher/src/backend/NodeConnection.js
Labels: bug

#493 FIX: set default values when necessary on setup
  controls/roles/setup/tasks/main.yml
Labels: bug

#494 FIX: remove duplication of key "until"
  controls/roles/manage-service/molecule/ssv-teku/verify.yml
Labels: bug

#514 FIX: installing all packages at once
  controls/roles/setup/tasks/docker-ubuntu.yaml
  controls/roles/ssv-key-generator/molecule/default/prepare.yml
Labels: bug

#517 Fix molecule prysm verify
  .github/workflows/test-molecule.yml
  controls/roles/validator-import-api/molecule/prysm/verify.yml
  controls/roles/validator-list-api/molecule/prysm/verify.yml
Labels: bug

#515 FIX: supporting sudo user
  launcher/src/backend/NodeConnection.js
  launcher/src/backend/NodeConnection.test.js
  launcher/src/backend/OneClickInstall.js
  launcher/src/backend/SSHService.js
  launcher/src/backend/ValidatorAccountManager.js
  launcher/src/backend/ethereum-services/NimbusBeaconService.int.js
  launcher/src/backend/ethereum-services/PrysmBeaconService.int.js
  launcher/src/backend/ethereum-services/TekuBeaconService.int.js
  launcher/src/background.js
  launcher/src/stereumservice.js
Labels: bug

#534 ADD: Blox SSV key pair replacement
  launcher/src/backend/NodeConnection.js
  launcher/src/backend/ValidatorAccountManager.js
  launcher/src/background.js
  launcher/src/components/UI/services-modal/SecretkeyRegister.vue
  launcher/src/components/UI/services-modal/SsvModal.vue
  launcher/src/store/ControlService.js
Labels: enhancement

#547 [README] Add GitPOAP Badge to Display Number of Minted GitPOAPs for Contributors
  README.md
Labels: documentation

#553 FIX: Small fixes bundle
  .github/workflows/test-molecule.yml
  controls/roles/configure-firewall/tasks/packages.yaml
Labels: bug, enhancement

#554 ADD: update-os & wiring with unattended update
  controls/roles/configure-updates/tasks/main.yml
  controls/roles/update-os/.yamllint
  controls/roles/update-os/molecule/default/converge.yml
  controls/roles/update-os/molecule/default/create.yml
  controls/roles/update-os/molecule/default/destroy.yml
  controls/roles/update-os/molecule/default/molecule.yml
  controls/roles/update-os/molecule/default/playbook.yml
  controls/roles/update-os/molecule/default/prepare.yml
  controls/roles/update-os/molecule/default/verify.yml
  controls/roles/update-os/molecule/run-stereum-service-update/converge.yml
  controls/roles/update-os/molecule/run-stereum-service-update/create.yml
  controls/roles/update-os/molecule/run-stereum-service-update/destroy.yml
  controls/roles/update-os/molecule/run-stereum-service-update/molecule.yml
  controls/roles/update-os/molecule/run-stereum-service-update/playbook.yml
  controls/roles/update-os/molecule/run-stereum-service-update/prepare.yml
  controls/roles/update-os/molecule/run-stereum-service-update/verify.yml
  controls/roles/update-os/tasks/main.yml
  controls/roles/update-stereum/tasks/main.yml
  controls/stereum-services-update.sh
  controls/unattended-update.sh
Labels: enhancement

#559 Small fixes bundle
  controls/roles/configure-firewall/molecule/default/molecule.yml
  controls/roles/configure-firewall/tasks/packages.yaml
  controls/roles/configure-updates/molecule/default/molecule.yml
  controls/roles/configure-updates/molecule/default/prepare.yml
  controls/roles/configure-updates/molecule/no-unattended-updates/molecule.yml
  controls/roles/fastsync/molecule/default/molecule.yml
  controls/roles/manage-service/molecule/monitor-besu/molecule.yml
  controls/roles/manage-service/molecule/monitor-bloxssv/molecule.yml
  controls/roles/manage-service/molecule/monitor-geth/molecule.yml
  controls/roles/manage-service/molecule/monitor-lighthouse/molecule.yml
  controls/roles/manage-service/molecule/monitor-nethermind/molecule.yml
  controls/roles/manage-service/molecule/monitor-nimbus/molecule.yml
  controls/roles/manage-service/molecule/monitor-prysm/molecule.yml
  controls/roles/manage-service/molecule/monitor-teku/molecule.yml
  controls/roles/manage-service/molecule/nethermind/molecule.yml
  controls/roles/manage-service/molecule/ssv-lighthouse/molecule.yml
  controls/roles/manage-service/molecule/ssv-nimbus/molecule.yml
  controls/roles/manage-service/molecule/ssv-prysm/molecule.yml
  controls/roles/manage-service/molecule/ssv-teku/molecule.yml
  controls/roles/manage-service/molecule/start-multiple/molecule.yml
  controls/roles/manage-service/molecule/start-stop/molecule.yml
  controls/roles/manage-service/molecule/start/molecule.yml
  controls/roles/manage-service/molecule/write-start/molecule.yml
  controls/roles/setup/molecule/default/molecule.yml
  controls/roles/setup/tasks/docker-ubuntu.yaml
  controls/roles/setup/tasks/update-os-ubuntu.yml
  controls/roles/ssv-key-generator/molecule/default/molecule.yml
  controls/roles/update-os/molecule/default/molecule.yml
  controls/roles/update-os/molecule/run-stereum-service-update/molecule.yml
  controls/roles/update-services/molecule/default/molecule.yml
  controls/roles/update-services/molecule/single-service/molecule.yml
  controls/roles/update-stereum/molecule/default/molecule.yml
  controls/roles/update-stereum/molecule/full/molecule.yml
  controls/roles/update-stereum/molecule/override/molecule.yml
  controls/roles/validator-delete-api/molecule/lighthouse/molecule.yml
  controls/roles/validator-delete-api/molecule/nimbus/molecule.yml
  controls/roles/validator-delete-api/molecule/prysm/molecule.yml
  controls/roles/validator-delete-api/molecule/teku/molecule.yml
  controls/roles/validator-fee-recipient-api/molecule/teku/molecule.yml
  controls/roles/validator-import-api/molecule/lighthouse/molecule.yml
  controls/roles/validator-import-api/molecule/nimbus/molecule.yml
  controls/roles/validator-import-api/molecule/prysm/molecule.yml
  controls/roles/validator-import-api/molecule/teku/molecule.yml
  controls/roles/validator-list-api/molecule/lighthouse/molecule.yml
  controls/roles/validator-list-api/molecule/nimbus/molecule.yml
  controls/roles/validator-list-api/molecule/prysm/molecule.yml
  controls/roles/validator-list-api/molecule/teku/molecule.yml
Labels: enhancement

#558 ADD: versions according to api
  launcher/src/backend/NodeConnection.js
  launcher/src/backend/OneClickInstall.js
  launcher/src/background.js
  launcher/src/components/UI/node-header/IconsNav.vue
  launcher/src/components/UI/node-header/MainNavbar.vue
  launcher/src/components/UI/node-header/UpdateModal.vue
  launcher/src/store/ControlService.js
  launcher/src/store/nodeHeader.js
Labels: enhancement

#561 ADD: running updates one by one
  launcher/public/img/icon/control/mainnetIconControl.png
  launcher/src/backend/NodeConnection.js
  launcher/src/backend/OneClickInstall.js
  launcher/src/backend/ethereum-services/BesuService.js
  launcher/src/backend/ethereum-services/GethService.js
  launcher/src/backend/ethereum-services/GethService.test.js
  launcher/src/backend/ethereum-services/PrometheusNodeExporterService.js
  launcher/src/backend/ethereum-services/PrysmBeaconService.js
  launcher/src/backend/ethereum-services/PrysmValidatorService.js
  launcher/src/background.js
  launcher/src/components/UI/click-installation/VueSelect.vue
  launcher/src/components/UI/node-header/IconsNav.vue
  launcher/src/components/UI/node-header/MainNavbar.vue
  launcher/src/components/UI/node-manage/NodeConfiguration.vue
  launcher/src/components/UI/node-manage/PresetModal.vue
  launcher/src/components/UI/the-control/AmsterdamComponent.vue
  launcher/src/components/UI/the-node/JournalNode.vue
  launcher/src/store/ControlService.js
  launcher/src/store/services.js
Labels: enhancement

#566 ADD: stereum notifications service
  .github/workflows/test-molecule.yml
  controls/defaults/stereum_defaults.yaml
  controls/roles/manage-service/molecule/notifications/converge.yml
  controls/roles/manage-service/molecule/notifications/create.yml
  controls/roles/manage-service/molecule/notifications/destroy.yml
  controls/roles/manage-service/molecule/notifications/molecule.yml
  controls/roles/manage-service/molecule/notifications/playbook.yml
  controls/roles/manage-service/molecule/notifications/prepare.yml
  controls/roles/manage-service/molecule/notifications/verify.yml
  controls/roles/manage-service/tasks/configure-grafana.yml
  controls/roles/manage-service/tasks/main.yml
  controls/roles/manage-service/tasks/write-grafana-configuration.yml
  controls/roles/manage-service/tasks/write-grafana-dashboards.yml
Labels: enhancement

#574 FIX: write grafana.ini automatically
  controls/roles/manage-service/files/grafana/grafana.ini
  controls/roles/manage-service/molecule/monitor-besu/converge.yml
  controls/roles/manage-service/molecule/monitor-bloxssv/converge.yml
  controls/roles/manage-service/molecule/monitor-geth/converge.yml
  controls/roles/manage-service/molecule/monitor-lighthouse/converge.yml
  controls/roles/manage-service/molecule/monitor-nethermind/converge.yml
  controls/roles/manage-service/molecule/monitor-nimbus/converge.yml
  controls/roles/manage-service/molecule/monitor-prysm/converge.yml
  controls/roles/manage-service/molecule/monitor-teku/converge.yml
  controls/roles/manage-service/molecule/notifications/converge.yml
  controls/roles/manage-service/tasks/main.yml
  controls/roles/manage-service/tasks/write-grafana-configuration.yml
  launcher/src/backend/ethereum-services/GrafanaService.js
Labels: bug

#578 ADD: auto reconnect after connection loss
  launcher/src/backend/SSHService.js
  launcher/src/background.js
  launcher/src/components/UI/node-header/MainNavbar.vue
  launcher/src/components/UI/the-staking/KeyTable.vue
  launcher/src/store/ControlService.js
Labels: enhancement

#586 FIX: Blox SSV config formatting
  launcher/src/backend/NodeConnection.js
  launcher/src/backend/OneClickInstall.js
  launcher/src/backend/ValidatorAccountManager.js
  launcher/src/backend/ethereum-services/BloxSSVService.js
  launcher/src/backend/ethereum-services/BloxSSVService.test.js
  launcher/src/background.js
Labels: bug

#589 REFACTOR: monitoring on Control-Page
  launcher/src/backend/Monitoring.js
  launcher/src/backend/NodeConnection.js
  launcher/src/backend/OneClickInstall.js
  launcher/src/backend/TaskManager.js
  launcher/src/background.js
  launcher/src/components/UI/node-header/IconsNav.vue
  launcher/src/components/UI/node-header/MainNavbar.vue
  launcher/src/components/UI/node-manage/NodeConfiguration.vue
  launcher/src/components/UI/server-connection/FormSetup.vue
  launcher/src/components/UI/the-control/MachineName.vue
  launcher/src/components/UI/the-control/TheCpu.vue
  launcher/src/components/UI/the-control/TheHard.vue
  launcher/src/components/UI/the-control/TheNetwork.vue
  launcher/src/components/UI/the-control/TheRam.vue
  launcher/src/components/UI/the-node/JournalNode.vue
  launcher/src/pages/TheControl.vue
  launcher/src/store/theControl.js
Labels: bug, enhancement

#592 Readme update
  README.md
Labels: documentation
