Repository stereum-dev/ethereum-node, pull requests merged in 2022-08, with the labels that each got.

#603 ADD: key import error handling
  launcher/src/backend/ValidatorAccountManager.js
  launcher/src/components/UI/node-manage/NodeConfiguration.vue
  launcher/src/components/UI/the-staking/FinishModal.vue
  launcher/src/components/UI/the-staking/KeyTable.vue
  launcher/src/store/theStaking.js
Labels: bug

#604 UPDATE: Integration tests, replace Math.random with crypto
  launcher/src/backend/StringUtils.js
  launcher/src/backend/ethereum-services/LighthouseBeaconService.int.js
  launcher/src/backend/ethereum-services/PrysmBeaconService.int.js
  launcher/src/backend/ethereum-services/TekuBeaconService.int.js
Labels: bug

#615 FIX: Service name (molecule tests) & engine.jwt gen fix
  .github/workflows/test-molecule.yml
  controls/roles/manage-service/molecule/ssv-lighthouse/converge.yml
  controls/roles/manage-service/molecule/ssv-lighthouse/prepare.yml
  controls/roles/manage-service/molecule/ssv-nimbus/converge.yml
  controls/roles/manage-service/molecule/ssv-nimbus/prepare.yml
  controls/roles/manage-service/molecule/ssv-prysm/converge.yml
  controls/roles/manage-service/molecule/ssv-prysm/prepare.yml
  controls/roles/manage-service/molecule/ssv-teku/converge.yml
  controls/roles/manage-service/molecule/ssv-teku/prepare.yml
  controls/roles/manage-service/molecule/start-multiple/prepare.yml
  controls/roles/manage-service/molecule/start-stop/prepare.yml
  controls/roles/manage-service/molecule/start/prepare.yml
  controls/roles/manage-service/molecule/write-start/converge.yml
  controls/roles/manage-service/tasks/main.yml
Labels: bug

#623 FIX: molecule tests & merge
  .github/workflows/test-molecule.yml
  controls/defaults/stereum_defaults.yaml
  controls/roles/fastsync/.travis.yml
  controls/roles/fastsync/.yamllint
  controls/roles/fastsync/molecule/default/converge.yml
  controls/roles/fastsync/molecule/default/create.yml
  controls/roles/fastsync/molecule/default/destroy.yml
  controls/roles/fastsync/molecule/default/molecule.yml
  controls/roles/fastsync/molecule/default/playbook.yml
  controls/roles/fastsync/molecule/default/prepare.yml
  controls/roles/fastsync/molecule/default/verify.yml
  controls/roles/fastsync/tasks/main.yml
  controls/roles/fastsync/tests/inventory
  controls/roles/fastsync/tests/test.yml
  controls/roles/fastsync/vars/main.yml
  controls/roles/manage-service/molecule/geth-teku/converge.yml
  controls/roles/manage-service/molecule/monitor-teku/prepare.yml
  controls/roles/manage-service/molecule/nethermind/converge.yml
  controls/roles/manage-service/molecule/nethermind/create.yml
  controls/roles/manage-service/molecule/nethermind/destroy.yml
  controls/roles/manage-service/molecule/nethermind/molecule.yml
  controls/roles/manage-service/molecule/nethermind/playbook.yml
  controls/roles/manage-service/molecule/nethermind/prepare.yml
  controls/roles/manage-service/molecule/nethermind/verify.yml
  controls/roles/manage-service/molecule/ssv-teku/prepare.yml
  controls/roles/manage-service/molecule/teku-geth/converge.yml
  controls/roles/validator-delete-api/molecule/teku/prepare.yml
  controls/roles/validator-fee-recipient-api/molecule/teku/prepare.yml
  controls/roles/validator-import-api/molecule/teku/prepare.yml
  controls/roles/validator-list-api/molecule/teku/prepare.yml
Labels: bug

#632 FIX: readme update
  README.md
Labels: documentation

#641 ADD: new ssv.network dashboards
  controls/roles/manage-service/files/grafana/BloxSSVService/dashboards/ssv-network-operator.json
  controls/roles/manage-service/files/grafana/BloxSSVService/dashboards/ssv-network-validator.json
  controls/roles/manage-service/files/grafana/BloxSSVService/dashboards/ssv-operator-node.json
Labels: enhancement

#644 ADD: fee recipient option to validator services
  launcher/src/backend/ethereum-services/LighthouseValidatorService.js
  launcher/src/backend/ethereum-services/NimbusBeaconService.js
  launcher/src/backend/ethereum-services/PrysmValidatorService.js
  launcher/src/backend/ethereum-services/TekuBeaconService.js
  launcher/src/components/UI/the-node/TheExpert.vue
  launcher/src/store/services.js
Labels: enhancement

#645 ADD: Update Panel
  launcher/public/img/icon/click-installation/BLOX_SSV.png
  launcher/public/img/icon/click-installation/ssv-network.png
  launcher/public/img/icon/header-icons/search.png
  launcher/public/img/icon/header-icons/search2.png
  launcher/public/img/icon/node-journal-icons/download1.png
  launcher/public/img/icon/plugin-icons/Other/ssv-network.png
  launcher/src/background.js
  launcher/src/components/UI/node-header/IconsNav.vue
  launcher/src/components/UI/node-header/UpdateModal.vue
  launcher/src/components/UI/node-header/UpdatePanel.vue
  launcher/src/components/UI/node-header/UpdateWaiting.vue
  launcher/src/components/UI/services-modal/GrafanaModal.vue
  launcher/src/components/UI/services-modal/PrometheusModal.vue
  launcher/src/components/UI/services-modal/SsvModal.vue
  launcher/src/components/UI/the-staking/KeyTable.vue
  launcher/src/store/clickInstallation.js
  launcher/src/store/nodeManage.js
  launcher/src/store/services.js
Labels: enhancement

#647 ADD: Links to SSV Module, Checkpoint Sync
  launcher/public/img/icon/the-staking/loading.gif
  launcher/src/backend/OneClickInstall.js
  launcher/src/backend/ValidatorAccountManager.js
  launcher/src/backend/ethereum-services/LighthouseBeaconService.js
  launcher/src/backend/ethereum-services/NimbusBeaconService.js
  launcher/src/backend/ethereum-services/PrysmBeaconService.js
  launcher/src/backend/ethereum-services/TekuBeaconService.js
  launcher/src/background.js
  launcher/src/components/UI/plugin-installation/VerifyInstallation.vue
  launcher/src/components/UI/services-modal/SsvDashboard.vue
  launcher/src/components/UI/the-staking/KeyTable.vue
  launcher/src/store/ControlService.js
Labels: enhancement

#656 FIX: Molecule remove fixed geth
  controls/defaults/stereum_defaults.yaml
  controls/roles/manage-service/molecule/monitor-lighthouse/molecule.yml
  controls/roles/manage-service/molecule/monitor-lighthouse/prepare.yml
  controls/roles/manage-service/molecule/monitor-nimbus/molecule.yml
  controls/roles/manage-service/molecule/monitor-nimbus/prepare.yml
  controls/roles/manage-service/molecule/monitor-prysm/molecule.yml
  controls/roles/manage-service/molecule/monitor-prysm/prepare.yml
  controls/roles/manage-service/molecule/monitor-ssvnetwork/molecule.yml
  controls/roles/manage-service/molecule/monitor-ssvnetwork/prepare.yml
  controls/roles/manage-service/molecule/monitor-ssvnetwork/verify.yml
  controls/roles/manage-service/molecule/ssv-lighthouse/molecule.yml
  controls/roles/manage-service/molecule/ssv-lighthouse/prepare.yml
  controls/roles/manage-service/molecule/ssv-lighthouse/verify.yml
  controls/roles/manage-service/molecule/ssv-nimbus/molecule.yml
  controls/roles/manage-service/molecule/ssv-nimbus/prepare.yml
  controls/roles/manage-service/molecule/ssv-nimbus/verify.yml
  controls/roles/manage-service/molecule/ssv-prysm/create.yml
  controls/roles/manage-service/molecule/ssv-prysm/molecule.yml
  controls/roles/manage-service/molecule/ssv-prysm/prepare.yml
  controls/roles/manage-service/molecule/ssv-prysm/verify.yml
  controls/roles/manage-service/molecule/ssv-teku/create.yml
  controls/roles/manage-service/molecule/ssv-teku/molecule.yml
  controls/roles/manage-service/molecule/ssv-teku/prepare.yml
  controls/roles/manage-service/molecule/ssv-teku/verify.yml
  controls/roles/update-os/molecule/default/molecule.yml
  controls/roles/update-os/molecule/run-stereum-service-update/molecule.yml
Labels: bug

#664 FIX: issues with various dashboards
  controls/roles/manage-service/files/grafana/BesuService/dashboards/besu-overview_rev5.json
  controls/roles/manage-service/files/grafana/LighthouseBeaconService/dashboards/BeaconProcessing.json
  controls/roles/manage-service/files/grafana/LighthouseBeaconService/dashboards/Database.json
  controls/roles/manage-service/files/grafana/LighthouseBeaconService/dashboards/ForkChoice.json
  controls/roles/manage-service/files/grafana/LighthouseBeaconService/dashboards/Slasher.json
  controls/roles/manage-service/files/grafana/LighthouseBeaconService/dashboards/Summary.json
  controls/roles/manage-service/files/grafana/LighthouseBeaconService/dashboards/Sync.json
  controls/roles/manage-service/files/grafana/LighthouseValidatorService/dashboards/ValidatorClient.json
  controls/roles/manage-service/files/grafana/LighthouseValidatorService/dashboards/ValidatorMonitor.json
  controls/roles/manage-service/files/grafana/NethermindService/dashboards/nethermind.json
  controls/roles/manage-service/files/grafana/NimbusBeaconService/dashboards/beacon_nodes_Grafana_dashboard.json
  controls/roles/manage-service/files/grafana/TekuBeaconService/dashboards/teku_single.json
Labels: bug

#670 FIX: black screen after build
  launcher/src/router/index.js
Labels: bug

#690 FIX: remove ssv network contract of config file
  launcher/src/backend/ethereum-services/SSVNetworkService.js
Labels: bug

#695 FIX: adjust ssv network shifu domains
  controls/defaults/stereum_defaults.yaml
  controls/roles/manage-service/molecule/monitor-ssvnetwork/prepare.yml
  controls/roles/manage-service/molecule/ssv-lighthouse/converge.yml
  controls/roles/manage-service/molecule/ssv-lighthouse/verify.yml
  controls/roles/manage-service/molecule/ssv-nimbus/converge.yml
  controls/roles/manage-service/molecule/ssv-nimbus/verify.yml
  controls/roles/manage-service/molecule/ssv-prysm/converge.yml
  controls/roles/manage-service/molecule/ssv-prysm/verify.yml
  controls/roles/manage-service/molecule/ssv-teku/converge.yml
  controls/roles/manage-service/molecule/ssv-teku/verify.yml
  controls/roles/ssv-key-generator/molecule/default/converge.yml
  controls/roles/ssv-key-generator/tasks/main.yaml
  launcher/src/backend/ValidatorAccountManager.js
  launcher/src/backend/ethereum-services/SSVNetworkService.js
  launcher/src/backend/ethereum-services/SSVNetworkService.test 2.js
  launcher/src/backend/ethereum-services/SSVNetworkService.test.js
  launcher/src/components/UI/services-modal/SsvModal.vue
Labels: bug

#697 FIX: make sure to install git on setup
  launcher/src/backend/NodeConnection.js
Labels: bug

#715 ADD: prometheus node exporter full dashboard
  controls/roles/manage-service/files/grafana/PrometheusNodeExporterService/dashboards/node_exporter_full.json
Labels: enhancement
