Repository stereum-dev/ethereum-node, pull requests merged in 2022-06, with the labels that each got.

#383 ADD: docker cleanup after updates #334
  controls/roles/update-services/molecule/default/verify.yml
  controls/roles/update-services/molecule/single-service/verify.yml
  controls/roles/update-services/tasks/main.yml
Labels: enhancement

#388 FIX: ssh listening ports #333
  controls/roles/configure-firewall/tasks/ufw.yaml
Labels: bug

#381 ADD: patches for updates
  controls/finishUpdate.yaml
  controls/unattended-update.sh
Labels: enhancement

#411 FIX: update readme
  README.md
Labels: documentation

#425 FIX: ssv-key-generator writes correct key-values
  controls/roles/manage-service/molecule/monitor-bloxssv/prepare.yml
  controls/roles/ssv-key-generator/tasks/main.yaml
Labels: bug

#432 FIX: molecule tests
  controls/roles/manage-service/molecule/ssv-prysm/prepare.yml
  controls/roles/manage-service/molecule/ssv-prysm/verify.yml
  controls/roles/validator-delete-api/molecule/prysm/prepare.yml
  controls/roles/validator-delete-api/molecule/prysm/verify.yml
Labels: bug

#455 ADD: prometheus automized config generation
  controls/roles/manage-service/molecule/monitor-bloxssv/converge.yml
  controls/roles/manage-service/molecule/monitor-bloxssv/prepare.yml
  controls/roles/manage-service/molecule/monitor-bloxssv/verify.yml
  controls/roles/manage-service/molecule/monitor-geth/converge.yml
  controls/roles/manage-service/molecule/monitor-geth/prepare.yml
  controls/roles/manage-service/molecule/monitor-geth/verify.yml
  controls/roles/manage-service/molecule/monitor-lighthouse/converge.yml
  controls/roles/manage-service/molecule/monitor-lighthouse/prepare.yml
  controls/roles/manage-service/molecule/monitor-lighthouse/verify.yml
  controls/roles/manage-service/molecule/monitor-nimbus/converge.yml
  controls/roles/manage-service/molecule/monitor-nimbus/prepare.yml
  controls/roles/manage-service/molecule/monitor-nimbus/verify.yml
  controls/roles/manage-service/molecule/monitor-prysm/converge.yml
  controls/roles/manage-service/molecule/monitor-prysm/prepare.yml
  controls/roles/manage-service/molecule/monitor-prysm/verify.yml
  controls/roles/manage-service/molecule/monitor-teku/converge.yml
  controls/roles/manage-service/molecule/monitor-teku/prepare.yml
  controls/roles/manage-service/molecule/monitor-teku/verify.yml
  controls/roles/manage-service/tasks/main.yml
  controls/roles/manage-service/tasks/write-prometheus-configuration.yml
  controls/roles/manage-service/templates/prometheus.yml
  launcher/src/backend/ethereum-services/PrometheusService.js
  launcher/src/backend/ethereum-services/PrometheusService.test.js
Labels: enhancement

#457 FIX: getting stuck on connecting animation
  launcher/src/components/UI/plugin-installation/VerifyInstallation.vue
  launcher/src/components/layers/FormSetup.vue
Labels: bug

#463 ADD: Grafana provisioning in ansible
  controls/roles/manage-service/files/grafana/BloxSSVService/dashboards/ssv-operator-node.json
  controls/roles/manage-service/files/grafana/GethService/dashboards/geth.json
  controls/roles/manage-service/files/grafana/LighthouseBeaconService/dashboards/BeaconProcessing.json
  controls/roles/manage-service/files/grafana/NimbusBeaconService/dashboards/beacon_nodes_Grafana_dashboard.json
  controls/roles/manage-service/files/grafana/PrysmBeaconService/dashboards/big_amount_validators.json
  controls/roles/manage-service/files/grafana/PrysmBeaconService/dashboards/multiple_source.json
  controls/roles/manage-service/files/grafana/PrysmBeaconService/dashboards/small_amount_validators.json
  controls/roles/manage-service/files/grafana/TekuBeaconService/dashboards/teku_single.json
  controls/roles/manage-service/molecule/monitor-bloxssv/converge.yml
  controls/roles/manage-service/molecule/monitor-geth/converge.yml
  controls/roles/manage-service/molecule/monitor-lighthouse/converge.yml
  controls/roles/manage-service/molecule/monitor-nimbus/converge.yml
  controls/roles/manage-service/molecule/monitor-prysm/converge.yml
  controls/roles/manage-service/molecule/monitor-teku/converge.yml
  controls/roles/manage-service/molecule/monitor-teku/prepare.yml
  controls/roles/manage-service/tasks/write-grafana-configuration.yml
  controls/roles/manage-service/templates/prometheus.yml
  launcher/src/backend/OneClickInstall.js
  launcher/src/backend/ServiceManager.js
Labels: enhancement
