Repository stereum-dev/ethereum-node, pull requests merged in 2022-10, with the labels that each got.

#812 FIX: nethermind sync
  launcher/src/backend/OneClickInstall.js
  launcher/src/backend/ethereum-services/NethermindService.js
Labels: bug

#802 FIX: Copy buttons, add node exporter, qol changes and fixes
  controls/roles/delete-service/tasks/main.yml
  launcher/public/img/icon/plugin-icons/Other/PrometheusNodeExporter-s.png
  launcher/public/img/icon/plugin-icons/Other/PrometheusNodeExporter.png
  launcher/src/backend/Monitoring.js
  launcher/src/backend/ServiceManager.js
  launcher/src/backend/ValidatorAccountManager.js
  launcher/src/background.js
  launcher/src/components/UI/node-header/MainNavbar.vue
  launcher/src/components/UI/node-manage/AddPanel.vue
  launcher/src/components/UI/node-manage/ChangeConfirm.vue
  launcher/src/components/UI/node-manage/ModifyPanel.vue
  launcher/src/components/UI/node-manage/NodeConfiguration.vue
  launcher/src/components/UI/node-manage/ServicePlugin.vue
  launcher/src/components/UI/node-manage/SwitchNetwork.vue
  launcher/src/components/UI/plugin-installation/VerifyInstallation.vue
  launcher/src/components/UI/plugin-installation/WarningModal.vue
  launcher/src/components/UI/services-modal/RegisterSsv.vue
  launcher/src/components/UI/services-modal/SsvDashboard.vue
  launcher/src/components/UI/task-manager/SubTasks.vue
  launcher/src/components/UI/the-node/NodeGrid.vue
  launcher/src/components/UI/the-node/NodeService.vue
  launcher/src/components/UI/the-staking/DisplayValidators.vue
  launcher/src/components/UI/the-staking/KeyTable.vue
  launcher/src/components/UI/the-staking/TimeReward.vue
  launcher/src/components/layers/NodeSetupConfig.vue
  launcher/src/pages/NodeManage.vue
  launcher/src/pages/TheNode.vue
  launcher/src/store/ControlService.js
  launcher/src/store/nodeManage.js
  launcher/src/store/services.js
  launcher/src/store/theNode.js
  launcher/tests/unit/layers/NodeSetupConfig.spec.js
Labels: enhancement

#845 FIX: update version + features
  README.md
Labels: documentation

#859 FIX: geth losing state on start/stop
  controls/roles/manage-service/tasks/main.yml
Labels: bug
